Fix

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -3,20 +3,27 @@
 #=================================================
 # GENERIC START
 #=================================================
-
 # IMPORT GENERIC HELPERS
+#=================================================
+
+source _common.sh
 source /usr/share/yunohost/helpers
 
+#=================================================
+# MANAGE SCRIPT FAILURE
+#=================================================
+
+ynh_clean_setup () {
+    ### Remove this function if there's nothing to clean before calling the remove script.
+    true
+}
 # Exit if an error occurs during the execution of the script
 ynh_abort_if_errors
 
-# Import common cmd
-source ./experimental_helper.sh
-source ./_common.sh
-
-ynh_script_progression --message="Validating installation parameters..."
-
+#=================================================
 # RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
 domain=$YNH_APP_ARG_DOMAIN
 path_url=$(ynh_normalize_url_path --path_url $YNH_APP_ARG_PATH)
 admin=$YNH_APP_ARG_ADMIN
@@ -28,11 +35,22 @@ sesha_install=$YNH_APP_ARG_SESHA_INSTALL
 ansel_install=$YNH_APP_ARG_ANSEL_INSTALL
 wicked_install=$YNH_APP_ARG_WICKED_INSTALL
 
-# Set variable
-final_path="/var/www/$app"
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
+#=================================================
+ynh_script_progression --message="Validating installation parameters..." --time --weight=1
 
+final_path=/var/www/$app
+test ! -e "$final_path" || ynh_die --message="This path already contains a folder"
+
+# Register (book) web path
+ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url
+
+#=================================================
 # STORE SETTINGS FROM MANIFEST
-ynh_script_progression --message="Storing installation settings..."
+#=================================================
+ynh_script_progression --message="Storing installation settings..." --time --weight=1
+
 ynh_app_setting_set --app $app --key admin --value $admin
 ynh_app_setting_set --app $app --key language --value $language
 ynh_app_setting_set --app $app --key final_path --value $final_path
@@ -43,11 +61,8 @@ ynh_app_setting_set --app $app --key sesha_install --value $sesha_install
 ynh_app_setting_set --app $app --key ansel_install --value $ansel_install
 ynh_app_setting_set --app $app --key wicked_install --value $wicked_install
 
-# Register (book) web path
-ynh_webpath_register --app $app --domain $domain --path_url $path_url
 
-# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
-test ! -e "$final_path" || ynh_die --message "This path already contains a folder"
+
 
 # Set list of optionnal app to install
 optionnal_apps_list=""
@@ -85,31 +100,45 @@ then
     locale-gen
 fi
 
-# INSTALL DEPENDENCIES
-ynh_script_progression --message="Installing dependencies..." --weight=7
-install_dependance
-
+#=================================================
+# STANDARD MODIFICATIONS
+#=================================================
 # CREATE A MYSQL DATABASE
-ynh_script_progression --message="Configuring MySQL database..."
+#=================================================
+ynh_script_progression --message="Creating a MySQL database..." --weight=2
+
 db_name=$(ynh_sanitize_dbid --db_name $app)
 db_user=$db_name
 ynh_app_setting_set --app $app --key db_name --value $db_name
 ynh_app_setting_set --app $app --key db_user --value $db_user
 ynh_mysql_setup_db --db_name $db_name --db_user $db_user
 
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+ynh_script_progression --message="Configuring system user..." --weight=2
+
 # Create a system user
-ynh_script_progression --message="Configuring system user..."
-ynh_system_user_create --username $app
+ynh_system_user_create --username=$app
+
+
 
 # Set execution for expect scripts
 chmod +x ../conf/init_horde_install.exp
 chmod +x ../conf/config_horde.exp
 
+
+
 # Install horde by pear
 ynh_script_progression --message="Creating base directory..."
+
+gollem_data_dir="/home/yunohost.app/$app"
+
 mkdir $final_path
 mkdir $final_path/data
 mkdir -p $gollem_data_dir
+
+
 
 ynh_script_progression --message="Installing sources files..." --weight=7
 
@@ -133,31 +162,83 @@ PHP_PEAR_SYSCONF_DIR=$final_path ../conf/config_horde.exp "$final_path" "$db_nam
 secret_key=$(grep 'secret_key' "$final_path/horde/config/conf.php" | cut -d"'" -f4)
 ynh_app_setting_set --app $app --key secret_key --value "$secret_key"
 
-# Patch the app
+#=================================================
+# PATCH THE APP
+#=================================================
 ynh_script_progression --message="Patching application..." --weight=7
-patch_app
 
-# Configure Horde
+    local old_dir=$(pwd)
+    (cd "$final_path/horde" && patch -p1 < $YNH_CWD/../sources/sso_auth.patch) || echo "Unable to apply patches"
+    cd $old_dir
+
+#=================================================
+# CONFIGURE HORDE
+#=================================================
 ynh_script_progression --message="Configuring application..." --weight=3
-config_horde
 
-# Create a dedicated nginx config
-ynh_script_progression --message="Configuring nginx..." --weight=1
-config_nginx
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/config/conf.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/imp/config/conf.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/config/registry.local.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/gollem/config/backends.local.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/ingo/config/backends.local.php"
 
-# Create a dedicated php-fpm config
-ynh_add_fpm_config
+    cp ../conf/horde_conf.php "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DOMAIN__ --replace_string "$domain" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __PATH__ --replace_string "$path_url" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __FINAL_PATH__ --replace_string "$final_path" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DB_NAME__ --replace_string "$db_name" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DB_USER__ --replace_string "$db_user" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DB_PASSWORD__ --replace_string "$db_pwd" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __ADMIN_USER__ --replace_string "$admin" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __SECRET_KEY__ --replace_string "$secret_key" --target_file "$final_path/horde/config/conf.php"
+    
+    cp ../conf/horde_imp_conf.php "$final_path/horde/imp/config/conf.php"
+    
+    cp ../conf/horde_registry.php "$final_path/horde/config/registry.local.php"
+    ynh_replace_string --match_string __PATH__ --replace_string "$path_url" --target_file "$final_path/horde/config/registry.local.php"
+
+    cp ../conf/gollem_backends.php "$final_path/horde/gollem/config/backends.local.php"
+    ynh_replace_string --match_string __GOLLEM_DATA_DIR__ --replace_string "$gollem_data_dir" --target_file "$final_path/horde/gollem/config/backends.local.php"
+
+    cp ../conf/ingo_backends.php "$final_path/horde/ingo/config/backends.local.php"
+
+    ynh_store_file_checksum --file "$final_path/horde/config/conf.php"
+    ynh_store_file_checksum --file "$final_path/horde/imp/config/conf.php"
+    ynh_store_file_checksum --file "$final_path/horde/config/registry.local.php"
+    ynh_store_file_checksum --file "$final_path/horde/gollem/config/backends.local.php"
+    ynh_store_file_checksum --file "$final_path/horde/ingo/config/backends.local.php"
 
 #=================================================
-# GENERIC FINALIZATION
+# NGINX CONFIGURATION
 #=================================================
+ynh_script_progression --message="Configuring NGINX web server..." --weight=2
 
+# Create a dedicated NGINX config
+ynh_add_nginx_config
+
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
+ynh_script_progression --message="Configuring PHP-FPM..." --weight=2
+
+ynh_add_fpm_config --phpversion=$YNH_PHP_VERSION --package="$extra_php_dependencies"
+phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)
+
+#=================================================
 # SECURE FILES AND DIRECTORIES
+#=================================================
 ynh_script_progression --message="Protecting directory..."
-set_permission
 
-# configure the sso
-ynh_script_progression --message="Configuring permissions..."
+chown -R www-data:$app $final_path
+chown -R www-data:$app $gollem_data_dir
+chmod u=rwX,g=rwX,o= -R $final_path
+chmod u=rwX,g=rwX,o= -R $gollem_data_dir
+
+#=================================================
+# SETUP SSOWAT
+#=================================================
+ynh_script_progression --message="Configuring SSOwat..." --time --weight=1
+
 if [ "$is_public" = "0" ];
 then	# Retire l'accès public
     ynh_app_setting_delete --app $app --key skipped_uris
@@ -165,10 +246,25 @@ else
     ynh_app_setting_set --app $app --key unprotected_uris --value "/"
 fi
 
+#=================================================
 # SETUP LOGROTATE
+#=================================================
 ynh_script_progression --message="Configuring log rotation..."
+
 ynh_use_logrotate $final_path/horde --nonappend --specific_user www-data/horde
 ynh_use_logrotate $final_path/horde/services --append --specific_user www-data/horde
 ynh_use_logrotate $final_path/horde/services/portal --append --specific_user www-data/horde
 
-ynh_script_progression --message="Installation of $app completed" --last
+#=================================================
+# RELOAD NGINX
+#=================================================
+ynh_script_progression --message="Reloading nginx web server..." --time --weight=1
+
+ynh_systemd_action --service_name=nginx --action=reload
+
+#=================================================
+# END OF SCRIPT
+#=================================================
+
+ynh_script_progression --message="Installation of $app completed" --time --last
+
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -3,20 +3,17 @@
 #=================================================
 # GENERIC START
 #=================================================
-
 # IMPORT GENERIC HELPERS
+#=================================================
+
+source _common.sh
 source /usr/share/yunohost/helpers
 
-# Exit if an error occurs during the execution of the script
-ynh_abort_if_errors
-
-# Import common cmd
-source ./experimental_helper.sh
-source ./_common.sh
-
-ynh_script_progression --message="Loading installation settings..."
-
+#=================================================
 # LOAD SETTINGS
+#=================================================
+ynh_script_progression --message="Loading installation settings..."  --weight=1
+
 domain=$(ynh_app_setting_get --app $app --key domain)
 path_url=$(ynh_normalize_url_path --path_url $(ynh_app_setting_get --app $app --key path))
 admin=$(ynh_app_setting_get --app $app --key admin)
@@ -28,9 +25,36 @@ db_name=$(ynh_app_setting_get --app $app --key db_name)
 db_user=$(ynh_app_setting_get --app $app --key db_user)
 db_pwd=$(ynh_app_setting_get --app $app --key mysqlpwd)
 
+#=================================================
+# CHECK VERSION
+#=================================================
+
+upgrade_type=$(ynh_check_app_version_changed)
+
+#=================================================
+# ENSURE DOWNWARD COMPATIBILITY
+#=================================================
+ynh_script_progression --message="Ensuring downward compatibility..."  --weight=2
+
+# If final_path doesn't exist, create it
+if [ -z "$final_path" ]; then
+	final_path=/var/www/$app
+	ynh_app_setting_set --app=$app --key=final_path --value=$final_path
+fi
+
+# If db_name doesn't exist, create it
+if [ -z "$db_name" ]; then
+	db_name=$(ynh_sanitize_dbid --db_name=$app)
+	ynh_app_setting_set --app=$app --key=db_name --value=$db_name
+fi
+
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
+ynh_script_progression --message="Backing up $app before upgrading (may take a while)..." --weight=7
+
 # Backup the current version of the app
 ynh_backup_before_upgrade
-
 ynh_clean_setup () {
 	# restore it if the upgrade fails
 	ynh_restore_upgradebackup
@@ -42,41 +66,104 @@ ynh_abort_if_errors
 # STANDARD UPGRADE STEPS
 #=================================================
 
-# INSTALL DEPENDENCIES
-ynh_script_progression --message="Upgrading dependencies..."
-install_dependance
 
-# Upgrade Horde by PEAR
+
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
 ynh_script_progression --message="Upgrading source files..." --weight=6
+
 pear_cmd="$final_path/pear/pear -c $final_path/pear.conf"
 $pear_cmd channel-update pear.horde.org
 $pear_cmd upgrade -R $final_path -a -B -c pear.horde.org || true
 
-# Patch the app
+#=================================================
+# PATCH THE APP
+#=================================================
 ynh_script_progression --message="Patching application..." --weight=7
-patch_app
 
-# Configure Horde
+    local old_dir=$(pwd)
+    (cd "$final_path/horde" && patch -p1 < $YNH_CWD/../sources/sso_auth.patch) || echo "Unable to apply patches"
+    cd $old_dir
+
+#=================================================
+# CONFIGURE HORDE
+#=================================================
 ynh_script_progression --message="Configuring application..." --weight=3
-config_horde
 
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/config/conf.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/imp/config/conf.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/config/registry.local.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/gollem/config/backends.local.php"
+    ynh_backup_if_checksum_is_different --file "$final_path/horde/ingo/config/backends.local.php"
+
+    cp ../conf/horde_conf.php "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DOMAIN__ --replace_string "$domain" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __PATH__ --replace_string "$path_url" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __FINAL_PATH__ --replace_string "$final_path" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DB_NAME__ --replace_string "$db_name" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DB_USER__ --replace_string "$db_user" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __DB_PASSWORD__ --replace_string "$db_pwd" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __ADMIN_USER__ --replace_string "$admin" --target_file "$final_path/horde/config/conf.php"
+    ynh_replace_string --match_string __SECRET_KEY__ --replace_string "$secret_key" --target_file "$final_path/horde/config/conf.php"
+    
+    cp ../conf/horde_imp_conf.php "$final_path/horde/imp/config/conf.php"
+    
+    cp ../conf/horde_registry.php "$final_path/horde/config/registry.local.php"
+    ynh_replace_string --match_string __PATH__ --replace_string "$path_url" --target_file "$final_path/horde/config/registry.local.php"
+
+    cp ../conf/gollem_backends.php "$final_path/horde/gollem/config/backends.local.php"
+    ynh_replace_string --match_string __GOLLEM_DATA_DIR__ --replace_string "$gollem_data_dir" --target_file "$final_path/horde/gollem/config/backends.local.php"
+
+    cp ../conf/ingo_backends.php "$final_path/horde/ingo/config/backends.local.php"
+
+    ynh_store_file_checksum --file "$final_path/horde/config/conf.php"
+    ynh_store_file_checksum --file "$final_path/horde/imp/config/conf.php"
+    ynh_store_file_checksum --file "$final_path/horde/config/registry.local.php"
+    ynh_store_file_checksum --file "$final_path/horde/gollem/config/backends.local.php"
+    ynh_store_file_checksum --file "$final_path/horde/ingo/config/backends.local.php"
+
+#=================================================
 # NGINX CONFIGURATION
-# Create a dedicated nginx config
-ynh_script_progression --message="Configuring nginx..." --weight=1
-config_nginx
+#=================================================
+ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=2
+
+# Create a dedicated NGINX config
+ynh_add_nginx_config
 
 #=================================================
 # GENERIC FINALIZATION
 #=================================================
-
 # SECURE FILES AND DIRECTORIES
+#=================================================
 ynh_script_progression --message="Protecting directory..."
-set_permission
 
+chown -R www-data:$app $final_path
+chown -R www-data:$app $gollem_data_dir
+chmod u=rwX,g=rwX,o= -R $final_path
+chmod u=rwX,g=rwX,o= -R $gollem_data_dir
+
+#=================================================
 # SETUP LOGROTATE
-ynh_script_progression --message="Configuring log rotation..."
+#=================================================
+ynh_script_progression --message="Configuring log rotation..." --time --weight=1
+
 ynh_use_logrotate $final_path/horde --nonappend --specific_user www-data/horde
 ynh_use_logrotate $final_path/horde/services --append --specific_user www-data/horde
 ynh_use_logrotate $final_path/horde/services/portal --append --specific_user www-data/horde
+
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# RELOAD NGINX
+#=================================================
+ynh_script_progression --message="Reloading NGINX web server..." --weight=2
+
+ynh_systemd_action --service_name=nginx --action=reload
+
+#=================================================
+# END OF SCRIPT
+#=================================================
 
 ynh_script_progression --message="Upgrade of $app completed" --last
